package sistema;

/**
 * 
 * @author yakor
 */
public class FrmMenuSistema extends javax.swing.JFrame {
    
    private PanelMapa panelMapa;
    private algoritmos.Busqueda motorBusqueda = new algoritmos.Busqueda();
    private algoritmos.MST motorMST = new algoritmos.MST();
    private algoritmos.RutaCorta motorRutas = new algoritmos.RutaCorta();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuSistema.class.getName());
        
    /**
     * Crea el form del menú y carga la tabla.
     */
    public FrmMenuSistema() {
        initComponents();
        
        inicializarMapa();
        llenarComboBoxes();
        
        lblCiudadPrim.setVisible(false);
        cmbCiudadPrim.setVisible(false);
    }

   private void inicializarMapa() {
       // Inclusión de panelmapa en el panel vacío que dejé
        panelMapa = new PanelMapa();

        pnlContenedorMapa.setLayout(new java.awt.BorderLayout());
        pnlContenedorMapa.add(panelMapa, java.awt.BorderLayout.CENTER);

        pnlContenedorMapa.revalidate();
        pnlContenedorMapa.repaint();
    }

    private void llenarComboBoxes() {
        cmbSemillaRecorridos.removeAllItems();
        cmbCiudadPrim.removeAllItems();
        cmbOrigen.removeAllItems();
        cmbDestino.removeAllItems();

        // Llenado de comboboxes
        for (elementos.Nodo n : panelMapa.getGrafo().getVertices()) {
            String ciudad = n.getMunicipio();
            cmbSemillaRecorridos.addItem(ciudad);
            cmbCiudadPrim.addItem(ciudad);
            cmbOrigen.addItem(ciudad);
            cmbDestino.addItem(ciudad);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRecorridos = new javax.swing.ButtonGroup();
        buttonGroupMST = new javax.swing.ButtonGroup();
        buttonGroupRutasCortas = new javax.swing.ButtonGroup();
        pnlOpciones = new javax.swing.JPanel();
        btnVisualizacion = new javax.swing.JButton();
        btnRecorridos = new javax.swing.JButton();
        btnArbolMinimo = new javax.swing.JButton();
        btnRutasCortas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlInferior = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlTarjetas = new javax.swing.JPanel();
        panelMST = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbtnKruskal = new javax.swing.JRadioButton();
        rbtnPrim = new javax.swing.JRadioButton();
        lblCiudadPrim = new javax.swing.JLabel();
        cmbCiudadPrim = new javax.swing.JComboBox<>();
        panelRutasCortas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rbtnDijkstra = new javax.swing.JRadioButton();
        rbtnBellmanFord = new javax.swing.JRadioButton();
        lblOrigen = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox<>();
        lblDestino = new javax.swing.JLabel();
        cmbDestino = new javax.swing.JComboBox<>();
        pnlVisualizacion = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNodos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAristas = new javax.swing.JTable();
        panelRecorridos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbSemillaRecorridos = new javax.swing.JComboBox<>();
        rbtnBFS = new javax.swing.JRadioButton();
        rbtnDFS = new javax.swing.JRadioButton();
        panelVacio = new javax.swing.JPanel();
        pnlContenedorMapa = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Ruta y Análisis de Grafos - Oaxaca");
        setBackground(new java.awt.Color(51, 102, 255));
        setResizable(false);

        pnlOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVisualizacion.setBackground(new java.awt.Color(51, 102, 255));
        btnVisualizacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVisualizacion.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizacion.setText("Visualización");
        btnVisualizacion.setToolTipText("Muestra el grafo original y la tabla general de nodos y aristas.");
        btnVisualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizacionActionPerformed(evt);
            }
        });

        btnRecorridos.setText("Recorridos");
        btnRecorridos.setToolTipText("Permite recorrer el grafo mediante Búsqueda en Anchura (BFS) o Profundidad (DFS).");
        btnRecorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridosActionPerformed(evt);
            }
        });

        btnArbolMinimo.setText("MST");
        btnArbolMinimo.setToolTipText("Calcula el Árbol de Expansión Mínima usando los algoritmos de Kruskal y Prim.");
        btnArbolMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbolMinimoActionPerformed(evt);
            }
        });

        btnRutasCortas.setText("Rutas Cortas");
        btnRutasCortas.setToolTipText("Encuentra el camino óptimo entre dos ciudades usando Dijkstra o Bellman-Ford.");
        btnRutasCortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutasCortasActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(51, 102, 255));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.setToolTipText("Muestra el análisis de complejidad temporal de cada algoritmo.");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnAyuda.setText("AYUDA");
        btnAyuda.setToolTipText("Muestra información del sistema y guía de uso.");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 50, 64));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOpcionesLayout.createSequentialGroup()
                        .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRecorridos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnArbolMinimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRutasCortas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisualizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArbolMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRutasCortas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pnlInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnConfirmar.setBackground(new java.awt.Color(51, 102, 255));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 50, 64));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlTarjetas.setLayout(new java.awt.CardLayout());

        panelMST.setName("panelMST"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("MENÚ ÁRBOL DE EXPANSIÓN MÍNIMA");

        buttonGroupMST.add(rbtnKruskal);
        rbtnKruskal.setSelected(true);
        rbtnKruskal.setText("Kruskal");
        rbtnKruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnKruskalActionPerformed(evt);
            }
        });

        buttonGroupMST.add(rbtnPrim);
        rbtnPrim.setText("Prim");
        rbtnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPrimActionPerformed(evt);
            }
        });

        lblCiudadPrim.setLabelFor(cmbCiudadPrim);
        lblCiudadPrim.setText("Ciudad Inicial:");

        cmbCiudadPrim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelMSTLayout = new javax.swing.GroupLayout(panelMST);
        panelMST.setLayout(panelMSTLayout);
        panelMSTLayout.setHorizontalGroup(
            panelMSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMSTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMSTLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelMSTLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelMSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMSTLayout.createSequentialGroup()
                                .addComponent(rbtnKruskal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnPrim))
                            .addGroup(panelMSTLayout.createSequentialGroup()
                                .addComponent(lblCiudadPrim)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCiudadPrim, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(288, Short.MAX_VALUE))))
        );
        panelMSTLayout.setVerticalGroup(
            panelMSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMSTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelMSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnKruskal)
                    .addComponent(rbtnPrim))
                .addGap(18, 18, 18)
                .addGroup(panelMSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudadPrim)
                    .addComponent(cmbCiudadPrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pnlTarjetas.add(panelMST, "mst");

        panelRutasCortas.setName("panelRutasCortas"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("MENÚ RUTAS MÁS CORTAS");

        buttonGroupRutasCortas.add(rbtnDijkstra);
        rbtnDijkstra.setSelected(true);
        rbtnDijkstra.setText("Dijkstra");
        rbtnDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDijkstraActionPerformed(evt);
            }
        });

        buttonGroupRutasCortas.add(rbtnBellmanFord);
        rbtnBellmanFord.setText("Bellman-Ford");
        rbtnBellmanFord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBellmanFordActionPerformed(evt);
            }
        });

        lblOrigen.setLabelFor(cmbCiudadPrim);
        lblOrigen.setText("Origen:");

        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDestino.setLabelFor(cmbCiudadPrim);
        lblDestino.setText("Destino:");

        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelRutasCortasLayout = new javax.swing.GroupLayout(panelRutasCortas);
        panelRutasCortas.setLayout(panelRutasCortasLayout);
        panelRutasCortasLayout.setHorizontalGroup(
            panelRutasCortasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutasCortasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRutasCortasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panelRutasCortasLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelRutasCortasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRutasCortasLayout.createSequentialGroup()
                                .addComponent(rbtnDijkstra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnBellmanFord))
                            .addGroup(panelRutasCortasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRutasCortasLayout.createSequentialGroup()
                                    .addComponent(lblOrigen)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRutasCortasLayout.createSequentialGroup()
                                    .addComponent(lblDestino)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        panelRutasCortasLayout.setVerticalGroup(
            panelRutasCortasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutasCortasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelRutasCortasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnDijkstra)
                    .addComponent(rbtnBellmanFord))
                .addGap(18, 18, 18)
                .addGroup(panelRutasCortasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigen)
                    .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRutasCortasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestino)
                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pnlTarjetas.add(panelRutasCortas, "rutas");

        pnlVisualizacion.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(751, 462));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(751, 462));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(750, 150));
        jScrollPane1.setRequestFocusEnabled(false);

        tblNodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNodos);

        jTabbedPane1.addTab("Nodos", jScrollPane1);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(750, 150));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(750, 150));

        tblAristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAristas.setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPane2.setViewportView(tblAristas);

        jTabbedPane1.addTab("Aristas", jScrollPane2);

        pnlVisualizacion.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pnlTarjetas.add(pnlVisualizacion, "visualizacion");

        panelRecorridos.setName("panelRecorridos"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("MENÚ RECORRIDOS");

        jLabel2.setLabelFor(cmbSemillaRecorridos);
        jLabel2.setText("Ciudad Semilla:");

        cmbSemillaRecorridos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroupRecorridos.add(rbtnBFS);
        rbtnBFS.setSelected(true);
        rbtnBFS.setText("BFS (Anchura)");

        buttonGroupRecorridos.add(rbtnDFS);
        rbtnDFS.setText("DFS (Profunidad)");

        javax.swing.GroupLayout panelRecorridosLayout = new javax.swing.GroupLayout(panelRecorridos);
        panelRecorridos.setLayout(panelRecorridosLayout);
        panelRecorridosLayout.setHorizontalGroup(
            panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecorridosLayout.createSequentialGroup()
                .addGroup(panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRecorridosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(panelRecorridosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRecorridosLayout.createSequentialGroup()
                                .addComponent(rbtnBFS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnDFS))
                            .addGroup(panelRecorridosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbSemillaRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        panelRecorridosLayout.setVerticalGroup(
            panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecorridosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnBFS)
                    .addComponent(rbtnDFS))
                .addGap(18, 18, 18)
                .addGroup(panelRecorridosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSemillaRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pnlTarjetas.add(panelRecorridos, "recorridos");

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        pnlTarjetas.add(panelVacio, "vacio");

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addComponent(pnlTarjetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addComponent(pnlTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContenedorMapa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlContenedorMapa.setPreferredSize(new java.awt.Dimension(1029, 713));
        pnlContenedorMapa.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlContenedorMapaLayout = new javax.swing.GroupLayout(pnlContenedorMapa);
        pnlContenedorMapa.setLayout(pnlContenedorMapaLayout);
        pnlContenedorMapaLayout.setHorizontalGroup(
            pnlContenedorMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContenedorMapaLayout.setVerticalGroup(
            pnlContenedorMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedorMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlContenedorMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:                                      
        motorBusqueda.detener();
        motorMST.detener();
        
        elementos.Grafo grafo = panelMapa.getGrafo();

        // Sistema de elección de panel
        java.awt.Component[] componentes = pnlTarjetas.getComponents();
        for (java.awt.Component componente : componentes) {
            if (componente.isVisible()) {

                String nombreTarjeta = componente.getName();

                // --- Panel RECORRIDOS ---
                if ("panelRecorridos".equals(nombreTarjeta)) {
                    String semilla = cmbSemillaRecorridos.getSelectedItem().toString();
                    
                    if (rbtnBFS.isSelected()) {
                        motorBusqueda.busquedaAnchura(semilla, grafo, panelMapa);
                    } else if (rbtnDFS.isSelected()) {
                        motorBusqueda.busquedaProfundidad(semilla, grafo, panelMapa);
                    }
                }

                // --- Panel MST ---
                else if ("panelMST".equals(nombreTarjeta)) {
                    if (rbtnKruskal.isSelected()) {
                        motorMST.mstKruskal(grafo, panelMapa);
                    } else if (rbtnPrim.isSelected()) {
                        String inicial = cmbCiudadPrim.getSelectedItem().toString();
                        motorMST.mstPrim(inicial, grafo, panelMapa);
                    }
                }

                // --- Panel RUTAS CORTAS ---
                else if ("panelRutasCortas".equals(nombreTarjeta)) {
                    String origen = cmbOrigen.getSelectedItem().toString();
                    String destino = cmbDestino.getSelectedItem().toString();

                    // Validar que no seleccionaron la misma ciudad
                    if (origen.equals(destino)) {
                        javax.swing.JOptionPane.showMessageDialog(this, 
                            "El origen y el destino no pueden ser la misma ciudad.", 
                            "Aviso", 
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                        return; 
                    }

                    if (rbtnDijkstra.isSelected()) {
                        // Llamada al método de Dijkstra
                        motorRutas.dijkstra(origen, destino, grafo, panelMapa);
                    } else if (rbtnBellmanFord.isSelected()) {
                        // Llamada al método de Bellman-Ford
                        motorRutas.bellmanFord(origen, destino, grafo, panelMapa);
                    }
                }

                break; 
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnRecorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridosActionPerformed
        // TODO add your handling code here: 
        
        // Selección de menú recorridos en el panel inferior
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlTarjetas.getLayout();
        layout.show(pnlTarjetas, "recorridos");
    }//GEN-LAST:event_btnRecorridosActionPerformed

    private void btnArbolMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbolMinimoActionPerformed
        // TODO add your handling code here:              
        
        // Selección de menú mst en el panel inferior
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlTarjetas.getLayout();
        layout.show(pnlTarjetas, "mst");
    }//GEN-LAST:event_btnArbolMinimoActionPerformed

    private void btnRutasCortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutasCortasActionPerformed
        // TODO add your handling code here:                                           
        
        // Selección de menú recorridos en el panel inferior
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlTarjetas.getLayout();
        layout.show(pnlTarjetas, "rutas");
    }//GEN-LAST:event_btnRutasCortasActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        // Sistema de detención de la corrida del algoritmo
        boolean seDetuvoBusqueda = motorBusqueda.detener();
        boolean seDetuvoMST = motorMST.detener();
        
        if (seDetuvoBusqueda || seDetuvoMST) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La ejecución del algoritmo ha sido cancelada.", 
                "Ejecución Detenida", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVisualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizacionActionPerformed
        // TODO add your handling code here:
        
        motorBusqueda.detener();
        motorMST.detener();

        elementos.Grafo grafo = panelMapa.getGrafo();
        grafo.resetearColores(); 
        for(elementos.Arista a : grafo.getAristas()) { a.setResaltada(false); }
        panelMapa.repaint();

        cargarTablasVisualizacion();
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlTarjetas.getLayout();
        layout.show(pnlTarjetas, "visualizacion"); 

        panelMapa.repaint();

    }//GEN-LAST:event_btnVisualizacionActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:

        motorBusqueda.detener();
        motorMST.detener();
        motorRutas.detener();

        elementos.Grafo grafo = panelMapa.getGrafo();
        grafo.resetearColores();
        panelMapa.repaint();

        StringBuilder reporte = new StringBuilder();
        reporte.append("ANÁLISIS DE COMPLEJIDAD TEMPORAL DE ALGORITMOS\n");
        reporte.append("========================================================================\n\n");

        reporte.append("1. Recorrido por Anchura (BFS)\n");
        reporte.append("   - Complejidad: O(V * E)\n");
        reporte.append("   - Descripción: Usualmente el recorrido por anchura tiene una complejidad temporal de O(V+E), pero debido al uso del Timer en el mismo método, que se ejecuta hasta que la cola queda vacía más el bucle for dentro del Timer, lleva a que pase de O(V+E) a O(V*E).\n\n");

        reporte.append("2. Recorrido por Profundidad (DFS)\n");
        reporte.append("   - Complejidad: O(V * E)\n");
        reporte.append("   - Descripción: Al igual que con el recorrido por anchura, la lógica del recorrido tiene una complejidad temporal de O(V+E), pero el uso del Timer hace que se deba recorrer todos los vértices y dentro del Timer hay un bucle for que causa que la complejidad temporal cambie.\n\n");

        reporte.append("3. Árbol de Expansión Mínima (Kruskal)\n");
        reporte.append("   - Complejidad: O(E log V)\n");
        reporte.append("   - Descripción: Tanto en el método original creado por Kruskal cómo la implementación hecha para el proyecto, esto es debido a que el ordenamiento de las aristas es lo que hace que la complejidad temporal sea O(E log V) y provoca que, tanto en el algoritmo original como en la implementación, la complejidad temporal sea la misma.\n\n");

        reporte.append("4. Árbol de Expansión Mínima (Prim)\n");
        reporte.append("   - Complejidad: O(E * V)\n");
        reporte.append("   - Descripción: A comparación del algoritmo original que tiene una complejidad temporal de O(E log V) o O(E+V log V) esta implementación tiene una complejidad temporal de O(E*V) debido a que no hace uso de una cola de prioridad, sino que realiza una búsqueda exhaustiva debido a que solo usamos 30 vértices.\n\n");

        reporte.append("5. Ruta más corta (Dijkstra)\n");
        reporte.append("   - Complejidad: O(V * E + V^2)\n");
        reporte.append("   - Descripción: El algoritmo original tiene una complejidad temporal de O(E log V) pero en la implementación, debido a que en el Timer se recorre las aristas de cada vértice por cada uno de los vértices en el grafo haciendo uso de una cola prioritaria.\n\n");

        reporte.append("6. Ruta más corta (Bellman-Ford)\n");
        reporte.append("   - Complejidad: O(V * E)\n");
        reporte.append("   - Descripción: La implementación del Bellman-Ford tiene la misma complejidad que el algoritmo original debido a que la lógica para buscar la ruta más corta ya que el Timer no recorre más veces los vértices ni las aristas y tampoco hace uso de una cola prioritaria como la implementación de Dijkstra.\n");

        javax.swing.JTextArea textArea = new javax.swing.JTextArea(reporte.toString());
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));
        textArea.setBackground(new java.awt.Color(248, 248, 248)); 
        textArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(750, 500));
        
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlTarjetas.getLayout();
        layout.show(pnlTarjetas, "vacio");

        javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Reportes de Complejidad Temporal", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnReportesActionPerformed

    private void rbtnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPrimActionPerformed
        // TODO add your handling code here:
        lblCiudadPrim.setVisible(true);
        cmbCiudadPrim.setVisible(true);
    }//GEN-LAST:event_rbtnPrimActionPerformed

    private void rbtnKruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnKruskalActionPerformed
        // TODO add your handling code here:
        lblCiudadPrim.setVisible(false);
        cmbCiudadPrim.setVisible(false);
    }//GEN-LAST:event_rbtnKruskalActionPerformed

    private void rbtnDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDijkstraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDijkstraActionPerformed

    private void rbtnBellmanFordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBellmanFordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnBellmanFordActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:                                 
        // código que crea un pop up de información
        
        javax.swing.JPopupMenu menuAyuda = new javax.swing.JPopupMenu();

        javax.swing.JMenuItem itemInfo = new javax.swing.JMenuItem("Información del programa");
        javax.swing.JMenuItem itemInstrucciones = new javax.swing.JMenuItem("Instrucciones de uso");

        itemInfo.addActionListener(e -> {
            String mensaje = "Sistema de Análisis de Grafos - Estado de Oaxaca\n\n"
                           + "Proyecto 3 para la materia de Análisis de Algoritmos.\n"
                           + "Permite visualizar y ejecutar algoritmos de recorridos,\n"
                           + "árboles de expansión mínima y rutas cortas sobre la\n"
                           + "red de carreteras de Oaxaca.\n\n"
                           + "Desarrollado por:\n"
                           + " - Axel Alberto Monge Valdez\n"
                           + " - Yazid Enrique Revilla Bernal\n"
                           + " - Dario Verdugo Tineo";

            javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Información del Programa", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        });

        itemInstrucciones.addActionListener(e -> {
            String instrucciones = "Instrucciones Generales:\n\n"
                                 + "1. Menú Lateral: Selecciona la categoría de algoritmo que deseas usar.\n"
                                 + "2. Panel Inferior: Selecciona el algoritmo específico y sus parámetros (ciudades).\n"
                                 + "3. Ejecución: Presiona 'CONFIRMAR' para ver el resultado dibujado en el mapa.\n"
                                 + "4. Visualización: Usa el botón 'Visualización' para limpiar el mapa y ver el grafo original.";

            javax.swing.JOptionPane.showMessageDialog(this, instrucciones, "Instrucciones de Uso", javax.swing.JOptionPane.QUESTION_MESSAGE);
        });

        menuAyuda.add(itemInstrucciones);
        menuAyuda.addSeparator();
        menuAyuda.add(itemInfo);

        menuAyuda.show(btnAyuda, 0, btnAyuda.getHeight());
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuSistema().setVisible(true));
    }
    
    private void cargarTablasVisualizacion() {
        elementos.Grafo grafo = panelMapa.getGrafo();
        
        tblNodos.setPreferredSize(null);
        tblAristas.setPreferredSize(null);

        // --- Configurar Tabla de Nodos ---
        String[] colNodos = {"Municipio", "Coord X", "Coord Y"};
        javax.swing.table.DefaultTableModel modelNodos = new javax.swing.table.DefaultTableModel(colNodos, 0);
        
        for (elementos.Nodo n : grafo.getVertices()) {
            Object[] fila = {n.getMunicipio(), n.getX(), n.getY()};
            modelNodos.addRow(fila);
        }
        tblNodos.setModel(modelNodos);

        // --- Configurar Tabla de Aristas ---
        String[] colAristas = {"Origen", "Destino", "Distancia (km)"};
        javax.swing.table.DefaultTableModel modelAristas = new javax.swing.table.DefaultTableModel(colAristas, 0);
        
        for (elementos.Arista a : grafo.getAristas()) {
            Object[] fila = {a.nodoOrigen.getMunicipio(), a.nodoDestino.getMunicipio(), (int)a.getPeso() + " km"};
            modelAristas.addRow(fila);
        }
        tblAristas.setModel(modelAristas);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArbolMinimo;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRecorridos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnRutasCortas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVisualizacion;
    private javax.swing.ButtonGroup buttonGroupMST;
    private javax.swing.ButtonGroup buttonGroupRecorridos;
    private javax.swing.ButtonGroup buttonGroupRutasCortas;
    private javax.swing.JComboBox<String> cmbCiudadPrim;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JComboBox<String> cmbSemillaRecorridos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCiudadPrim;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JPanel panelMST;
    private javax.swing.JPanel panelRecorridos;
    private javax.swing.JPanel panelRutasCortas;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JPanel pnlContenedorMapa;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlTarjetas;
    private javax.swing.JPanel pnlVisualizacion;
    private javax.swing.JRadioButton rbtnBFS;
    private javax.swing.JRadioButton rbtnBellmanFord;
    private javax.swing.JRadioButton rbtnDFS;
    private javax.swing.JRadioButton rbtnDijkstra;
    private javax.swing.JRadioButton rbtnKruskal;
    private javax.swing.JRadioButton rbtnPrim;
    private javax.swing.JTable tblAristas;
    private javax.swing.JTable tblNodos;
    // End of variables declaration//GEN-END:variables
}
