package sistema;

import elementos.Arista;
import elementos.Grafo;
import elementos.Nodo;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.util.List;

/**
 *
 * @author Dario
 */
public class PanelMapa extends javax.swing.JPanel {

    private Grafo grafo;
    private List<Nodo> rutaResaltada;
    private Image imagenFondo;

    public PanelMapa() {
        initComponents();
    
        java.net.URL imgUrl = getClass().getResource("/mapa_oaxaca.png");
        if (imgUrl != null) {
            this.imagenFondo = new javax.swing.ImageIcon(imgUrl).getImage();
        }

        this.grafo = new Grafo();
        inicializarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

 public Grafo getGrafo() {
        return this.grafo;
    }
    
    private void inicializarDatos() {
        grafo.agregarNodo("Tuxtepec", 520, 165);
        grafo.agregarNodo("Loma Bonita", 560, 185);
        grafo.agregarNodo("Huajuapan", 205, 205);
        grafo.agregarNodo("Nochixtlán", 330, 270);
        grafo.agregarNodo("Tlaxiaco", 240, 315);
        grafo.agregarNodo("Oaxaca", 430, 345); 
        grafo.agregarNodo("Atzompa", 400, 320);          
        grafo.agregarNodo("J. Amilpas", 410, 330);       
        grafo.agregarNodo("L. del Camino", 460, 330);    
        grafo.agregarNodo("C. Amilpas", 480, 345);       
        grafo.agregarNodo("A. de la Cal", 460, 365);     
        grafo.agregarNodo("Xoxocotlán", 415, 365);       
        grafo.agregarNodo("Cuilápam", 390, 380);         
        grafo.agregarNodo("Zaachila", 405, 400);         
        grafo.agregarNodo("V. Guerrero", 430, 415);      
        grafo.agregarNodo("Zimatlán", 385, 440);         
        grafo.agregarNodo("Ocotlán", 465, 440);          
        grafo.agregarNodo("Tlacolula", 525, 370);        
        grafo.agregarNodo("Miahuatlán", 460, 490);
        grafo.agregarNodo("Pinotepa Nal.", 170, 560); 
        grafo.agregarNodo("Río Grande", 275, 600); 
        grafo.agregarNodo("Pto. Escondido", 375, 640); 
        grafo.agregarNodo("Pochutla", 480, 635); 
        grafo.agregarNodo("Crucecita", 545, 650);            
        grafo.agregarNodo("Matías Romero", 760, 400);
        grafo.agregarNodo("Ixtepec", 720, 470);       
        grafo.agregarNodo("Tehuantepec", 710, 540);   
        grafo.agregarNodo("Juchitán", 760, 520);      
        grafo.agregarNodo("U. Hidalgo", 800, 505);    
        grafo.agregarNodo("Salina Cruz", 695, 595);
    
        grafo.agregarArista("Tehuantepec", "Ixtepec", 34);
        grafo.agregarArista("Ixtepec", "Matías Romero", 69);
        grafo.agregarArista("Tehuantepec", "Oaxaca", 249);
        grafo.agregarArista("Oaxaca", "Tlacolula", 31);
        grafo.agregarArista("Oaxaca", "Nochixtlán", 89);
        grafo.agregarArista("Nochixtlán", "Huajuapan", 99);
        grafo.agregarArista("Tuxtepec", "Oaxaca", 219);
        grafo.agregarArista("Oaxaca", "Miahuatlán", 103);
        grafo.agregarArista("Miahuatlán", "Pochutla", 105);
        grafo.agregarArista("Pochutla", "Pto. Escondido", 70);
        grafo.agregarArista("Pinotepa Nal.", "Pto. Escondido", 139);
        grafo.agregarArista("Pochutla", "Crucecita", 32);
        grafo.agregarArista("Crucecita", "Salina Cruz", 166);
        grafo.agregarArista("Pinotepa Nal.", "Río Grande", 48);
        grafo.agregarArista("Matías Romero", "Salina Cruz", 135);
        grafo.agregarArista("Tehuantepec", "Salina Cruz", 15);
        grafo.agregarArista("Oaxaca", "Huajuapan", 171);
        grafo.agregarArista("Tuxtepec", "Loma Bonita", 45);
        grafo.agregarArista("Loma Bonita", "Matías Romero", 145);
        grafo.agregarArista("Tlaxiaco", "Nochixtlán", 76);
        grafo.agregarArista("Tlaxiaco", "Pinotepa Nal.", 230);
        grafo.agregarArista("Juchitán", "Tehuantepec", 29);
        grafo.agregarArista("Juchitán", "Ixtepec", 17);
        grafo.agregarArista("Juchitán", "U. Hidalgo", 12);
        grafo.agregarArista("Oaxaca", "Xoxocotlán", 4);
        grafo.agregarArista("Oaxaca", "L. del Camino", 3);
        grafo.agregarArista("Oaxaca", "A. de la Cal", 8);
        grafo.agregarArista("Oaxaca", "Atzompa", 7);
        grafo.agregarArista("Oaxaca", "J. Amilpas", 6);
        grafo.agregarArista("Oaxaca", "C. Amilpas", 9);
        grafo.agregarArista("Xoxocotlán", "A. de la Cal", 7);
        grafo.agregarArista("Xoxocotlán", "Cuilápam", 10);
        grafo.agregarArista("L. del Camino", "J. Amilpas", 5);
        grafo.agregarArista("J. Amilpas", "C. Amilpas", 4);
        grafo.agregarArista("Atzompa", "L. del Camino", 6);
        grafo.agregarArista("Oaxaca", "Zaachila", 17);
        grafo.agregarArista("Xoxocotlán", "Zaachila", 15);
        grafo.agregarArista("Zaachila", "Cuilápam", 8);
        grafo.agregarArista("Zaachila", "V. Guerrero", 3);
        grafo.agregarArista("Oaxaca", "Zimatlán", 32);
        grafo.agregarArista("Zaachila", "Zimatlán", 18);
        grafo.agregarArista("Oaxaca", "Ocotlán", 35);
        grafo.agregarArista("Zimatlán", "Ocotlán", 22);
        grafo.agregarArista("Ocotlán", "Tlacolula", 30);
        grafo.agregarArista("Pinotepa Nal.", "Huajuapan", 286);
        grafo.agregarArista("Huajuapan", "Tlaxiaco", 121);
        grafo.agregarArista("Salina Cruz", "Miahuatlán", 181);
        grafo.agregarArista("Zimatlán", "Miahuatlán", 72);
    }

    public void setRuta(List<Nodo> ruta) {
        this.rutaResaltada = ruta;
        repaint();
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
        
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(java.awt.RenderingHints.KEY_TEXT_ANTIALIASING, java.awt.RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        
        if (imagenFondo != null) {
            g2.drawImage(imagenFondo, 0, 0, 1029, 713, this); 
        }
        
        // --- DIBUJO DEL CORTE DE PRIM ---
        boolean dibujandoPrim = grafo.getVertices().stream().anyMatch(Nodo::isEnConjuntoS);
        
        if (dibujandoPrim) {
            java.awt.geom.Area territorioS = new java.awt.geom.Area();
            
            int radio = 22; 
            int diametro = radio * 2;
            
            for (Nodo n : grafo.getVertices()) {
                if (n.isEnConjuntoS()) {
                    java.awt.geom.Ellipse2D.Double circulo = new java.awt.geom.Ellipse2D.Double(n.getX() - radio, n.getY() - radio, diametro, diametro);
                    territorioS.add(new java.awt.geom.Area(circulo)); 
                }
            }
            
            java.awt.BasicStroke trazoGrueso = new java.awt.BasicStroke(diametro, java.awt.BasicStroke.CAP_ROUND, java.awt.BasicStroke.JOIN_ROUND);
            
            for (Arista a : grafo.getAristas()) {
                if (a.isResaltada()) { 
                    java.awt.geom.Line2D.Double linea = new java.awt.geom.Line2D.Double(
                        a.getNodoOrigen().getX(), a.getNodoOrigen().getY(), 
                        a.getNodoDestino().getX(), a.getNodoDestino().getY()
                    );
                    java.awt.Shape formaLinea = trazoGrueso.createStrokedShape(linea);
                    territorioS.add(new java.awt.geom.Area(formaLinea));
                }
            }
            
            if (!territorioS.isEmpty()) {
                g2.setColor(new Color(40, 200, 80, 45)); 
                g2.fill(territorioS);
                
                float[] dash = {6.0f, 4.0f}; 
                g2.setStroke(new java.awt.BasicStroke(2.0f, java.awt.BasicStroke.CAP_ROUND, java.awt.BasicStroke.JOIN_ROUND, 10.0f, dash, 0.0f));
                g2.setColor(new Color(20, 150, 50, 220)); 
                g2.draw(territorioS);
            }
        }
        
        // --- ARISTAS Y PESOS ---
        boolean hayAnimacion = grafo.getAristas().stream().anyMatch(Arista::isResaltada);
        
        for (Arista a : grafo.getAristas()) {
            int x1 = a.nodoOrigen.getX();
            int y1 = a.nodoOrigen.getY();
            int x2 = a.nodoDestino.getX();
            int y2 = a.nodoDestino.getY();

            if (a.isResaltada()) {
                // Ruta confirmada (Línea roja gruesa)
                g2.setColor(new Color(50, 0, 0, 150)); 
                g2.setStroke(new java.awt.BasicStroke(5.5f, java.awt.BasicStroke.CAP_ROUND, java.awt.BasicStroke.JOIN_ROUND));
                g2.drawLine(x1, y1 + 2, x2, y2 + 2); 
                
                g2.setColor(new Color(255, 40, 40, 240)); 
                g2.setStroke(new java.awt.BasicStroke(4.0f, java.awt.BasicStroke.CAP_ROUND, java.awt.BasicStroke.JOIN_ROUND));
                
            } else if (a.isEnCorte()) {
                // Exploración (Línea punteada verde)
                float[] dash = {8.0f, 6.0f};
                g2.setColor(new Color(40, 180, 60, 220)); 
                g2.setStroke(new java.awt.BasicStroke(3.0f, java.awt.BasicStroke.CAP_ROUND, java.awt.BasicStroke.JOIN_ROUND, 10.0f, dash, 0.0f));
                
            } else {
                // Arista ignorada / en espera (Línea azul)
                g2.setColor(new Color(100, 150, 200, 90)); 
                g2.setStroke(new java.awt.BasicStroke(2.0f, java.awt.BasicStroke.CAP_ROUND, java.awt.BasicStroke.JOIN_ROUND));
            }
            g2.drawLine(x1, y1, x2, y2);

            // --- TEXTOS DE KM ---
            if (!hayAnimacion) {
                double dx = x2 - x1;
                double dy = y2 - y1;
                double distVisual = Math.hypot(dx, dy);
                
                if (distVisual > 30) {
                    int midX = (x1 + x2) / 2;
                    int midY = (y1 + y2) / 2;
                    
                    double nx = -dy / distVisual;
                    double ny = dx / distVisual;
                    
                    int separacion = 12;
                    int drawX = (int) (midX + nx * separacion);
                    int drawY = (int) (midY + ny * separacion);
                    
                    g2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 9));
                    String pesoTx = distVisual < 55 ? String.valueOf((int)a.getPeso()) : (int)a.getPeso() + " km";
                    
                    java.awt.FontMetrics fm = g2.getFontMetrics();
                    int textW = fm.stringWidth(pesoTx);
                    
                    g2.setColor(new Color(255, 255, 255, 200));
                    g2.drawString(pesoTx, drawX - (textW/2) - 1, drawY - 1);
                    g2.drawString(pesoTx, drawX - (textW/2) + 1, drawY + 1);
                    g2.drawString(pesoTx, drawX - (textW/2) - 1, drawY + 1);
                    g2.drawString(pesoTx, drawX - (textW/2) + 1, drawY - 1);
                    
                    g2.setColor(new Color(40, 70, 110)); 
                    g2.drawString(pesoTx, drawX - (textW/2), drawY);
                }
            }
        }
        
        // --- NODOS ---
        java.awt.Font fuenteNormal = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11);
        java.awt.Font fuenteCapital = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);

        for (Nodo n : grafo.getVertices()) {
            int x = n.getX();
            int y = n.getY();
            String nombre = n.getMunicipio();

            g2.setColor(new Color(0, 0, 0, 70));
            g2.fillOval(x - 6, y - 6, 20, 20);
            
            g2.setColor(n.getColor());
            g2.fillOval(x - 9, y - 9, 18, 18);
            
            g2.setColor(Color.DARK_GRAY);
            g2.setStroke(new java.awt.BasicStroke(2.0f));
            g2.drawOval(x - 9, y - 9, 18, 18);

            g2.setFont(nombre.equals("Oaxaca") ? fuenteCapital : fuenteNormal);
            int anchoTexto = g2.getFontMetrics().stringWidth(nombre);

            int textoX = x + 14; 
            int textoY = y + 4;

            if (nombre.equals("Oaxaca")) {
                textoX = x - (anchoTexto / 2); 
                textoY = y - 22;
            } 
            else if (nombre.equals("Atzompa")) {
                textoX = x - anchoTexto - 14;
                textoY = y + 15; 
            }
            else if (nombre.equals("J. Amilpas") || nombre.equals("C. Amilpas")) {
                textoX = x - (anchoTexto / 2);
                textoY = y - 24;
            }
            else if (nombre.equals("A. de la Cal")) {
                textoX = x + 14;
                textoY = y + 26;
            }
            else if (nombre.equals("L. del Camino")) {
                textoX = x + 14;
                textoY = y + 4;
            }
            else if (nombre.equals("Xoxocotlán") || nombre.equals("Zaachila") || nombre.equals("Cuilápam")) {
                textoX = x - anchoTexto - 14;
            }
            else if (nombre.equals("V. Guerrero") || nombre.equals("Ocotlán") || nombre.equals("Zimatlán")) {
                textoX = x - (anchoTexto / 2);
                textoY = y + 26;
            }
            else if (nombre.equals("Nochixtlán") || nombre.equals("Tuxtepec") || nombre.equals("Huajuapan")) {
                textoX = x - (anchoTexto / 2); 
                textoY = y - 16;
            }

            g2.setColor(new Color(255, 255, 255, 220));
            g2.drawString(nombre, textoX - 1, textoY - 1);
            g2.drawString(nombre, textoX + 1, textoY + 1);

            g2.setColor(nombre.equals("Oaxaca") ? new Color(180, 0, 0) : new Color(30, 40, 50));
            g2.drawString(nombre, textoX, textoY);
            
            // --- DIBUJAR TIEMPOS DFS (d / f) ---
            if (n.getTiempoDescubrimiento() > 0) {
                String textoTiempos = n.getTiempoDescubrimiento() + "/";
                if (n.getTiempoFinalizacion() > 0) {
                    textoTiempos += n.getTiempoFinalizacion();
                }
                
                g2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
                int anchoTiempos = g2.getFontMetrics().stringWidth(textoTiempos);
                
                int posX = x - (anchoTiempos / 2);
                int posY = y + 22; 
                
                g2.setColor(new Color(255, 255, 255, 220));
                g2.drawString(textoTiempos, posX - 1, posY - 1);
                g2.drawString(textoTiempos, posX + 1, posY + 1);
                g2.drawString(textoTiempos, posX - 1, posY + 1);
                g2.drawString(textoTiempos, posX + 1, posY - 1);
                
                g2.setColor(new Color(120, 0, 180)); 
                g2.drawString(textoTiempos, posX, posY);
            }
        }
    }
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

