package sistema;

import elementos.Arista;
import elementos.Grafo;
import elementos.Nodo;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.util.List;

/**
 *
 * @author Dario
 */
public class PanelMapa extends javax.swing.JPanel {

    private Grafo grafo;
    private List<Nodo> rutaResaltada;
    private Image imagenFondo;

    public PanelMapa() {
        initComponents();
    
        java.net.URL imgUrl = getClass().getResource("/mapa_oaxaca.png");
        if (imgUrl != null) {
            this.imagenFondo = new javax.swing.ImageIcon(imgUrl).getImage();
        }

        this.grafo = new Grafo();
        inicializarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public Grafo getGrafo() {
        return this.grafo;
    }
    
    private void inicializarDatos() {
        grafo.agregarNodo("Tuxtepec", 635, 190);
        grafo.agregarNodo("Loma Bonita", 680, 215);
        grafo.agregarNodo("Huajuapan", 320, 225);
        grafo.agregarNodo("Nochixtlán", 415, 330);
        grafo.agregarNodo("Tlaxiaco", 310, 395);
        grafo.agregarNodo("Oaxaca", 535, 425); 
        grafo.agregarNodo("Atzompa", 500, 390);          
        grafo.agregarNodo("J. Amilpas", 510, 405);       
        grafo.agregarNodo("L. del Camino", 570, 405);    
        grafo.agregarNodo("C. Amilpas", 595, 425);       
        grafo.agregarNodo("A. de la Cal", 570, 445);     
        grafo.agregarNodo("Xoxocotlán", 515, 445);       
        grafo.agregarNodo("Cuilápam", 485, 465);         
        grafo.agregarNodo("Zaachila", 500, 490);         
        grafo.agregarNodo("V. Guerrero", 535, 510);      
        grafo.agregarNodo("Zimatlán", 480, 540);         
        grafo.agregarNodo("Ocotlán", 575, 540);          
        grafo.agregarNodo("Tlacolula", 645, 455);        
        grafo.agregarNodo("Pinotepa Nal.", 215, 740); 
        grafo.agregarNodo("Río Grande", 340, 790); 
        grafo.agregarNodo("Pto. Escondido", 460, 820);    
        grafo.agregarNodo("Pochutla", 585, 830); 
        grafo.agregarNodo("Crucecita", 665, 850);           
        grafo.agregarNodo("Miahuatlán", 570, 610);
        grafo.agregarNodo("Matías Romero", 895, 440);
        grafo.agregarNodo("Ixtepec", 845, 570);
        grafo.agregarNodo("Tehuantepec", 835, 670); 
        grafo.agregarNodo("Juchitán", 955, 650); 
        grafo.agregarNodo("U. Hidalgo", 1005, 635); 
        grafo.agregarNodo("Salina Cruz", 850, 775);
    
        grafo.agregarArista("Tehuantepec", "Ixtepec", 34);
        grafo.agregarArista("Ixtepec", "Matías Romero", 69);
        grafo.agregarArista("Tehuantepec", "Oaxaca", 249);
        grafo.agregarArista("Oaxaca", "Tlacolula", 31);
        grafo.agregarArista("Oaxaca", "Nochixtlán", 89);
        grafo.agregarArista("Nochixtlán", "Huajuapan", 99);
        grafo.agregarArista("Tuxtepec", "Oaxaca", 219);
        grafo.agregarArista("Oaxaca", "Miahuatlán", 103);
        grafo.agregarArista("Miahuatlán", "Pochutla", 105);
        grafo.agregarArista("Pochutla", "Pto. Escondido", 70);
        grafo.agregarArista("Pinotepa Nal.", "Pto. Escondido", 139);
        grafo.agregarArista("Pochutla", "Crucecita", 32);
        grafo.agregarArista("Crucecita", "Salina Cruz", 166);
        grafo.agregarArista("Pinotepa Nal.", "Río Grande", 48);
        grafo.agregarArista("Matías Romero", "Salina Cruz", 135);
        grafo.agregarArista("Tehuantepec", "Salina Cruz", 15);
        grafo.agregarArista("Oaxaca", "Huajuapan", 171);
        grafo.agregarArista("Tuxtepec", "Loma Bonita", 45);
        grafo.agregarArista("Loma Bonita", "Matías Romero", 145);
        grafo.agregarArista("Tlaxiaco", "Nochixtlán", 76);
        grafo.agregarArista("Tlaxiaco", "Pinotepa Nal.", 230);
        grafo.agregarArista("Juchitán", "Tehuantepec", 29);
        grafo.agregarArista("Juchitán", "Ixtepec", 17);
        grafo.agregarArista("Juchitán", "U. Hidalgo", 12);
        grafo.agregarArista("Oaxaca", "Xoxocotlán", 4);
        grafo.agregarArista("Oaxaca", "L. del Camino", 3);
        grafo.agregarArista("Oaxaca", "A. de la Cal", 8);
        grafo.agregarArista("Oaxaca", "Atzompa", 7);
        grafo.agregarArista("Oaxaca", "J. Amilpas", 6);
        grafo.agregarArista("Oaxaca", "C. Amilpas", 9);
        grafo.agregarArista("Xoxocotlán", "A. de la Cal", 7);
        grafo.agregarArista("Xoxocotlán", "Cuilápam", 10);
        grafo.agregarArista("L. del Camino", "J. Amilpas", 5);
        grafo.agregarArista("J. Amilpas", "C. Amilpas", 4);
        grafo.agregarArista("Atzompa", "L. del Camino", 6);
        grafo.agregarArista("Oaxaca", "Zaachila", 17);
        grafo.agregarArista("Xoxocotlán", "Zaachila", 15);
        grafo.agregarArista("Zaachila", "Cuilápam", 8);
        grafo.agregarArista("Zaachila", "V. Guerrero", 3);
        grafo.agregarArista("Oaxaca", "Zimatlán", 32);
        grafo.agregarArista("Zaachila", "Zimatlán", 18);
        grafo.agregarArista("Oaxaca", "Ocotlán", 35);
        grafo.agregarArista("Zimatlán", "Ocotlán", 22);
        grafo.agregarArista("Ocotlán", "Tlacolula", 30);
        grafo.agregarArista("Pinotepa Nal.", "Huajuapan", 286);
        grafo.agregarArista("Huajuapan", "Tlaxiaco", 121);
        grafo.agregarArista("Salina Cruz", "Miahuatlán", 181);
        grafo.agregarArista("Zimatlán", "Miahuatlán", 72);
    }

    public void setRuta(List<Nodo> ruta) {
        this.rutaResaltada = ruta;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        if (imagenFondo != null) {
            g2.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
        }
        
        // --- Aristas ---
        for (Arista a : grafo.getAristas()) {
            if (a.isResaltada()) {
                // Ruta Activa
                g2.setColor(new Color(255, 60, 60, 220)); 
                g2.setStroke(new BasicStroke(4.5f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
            } else {
                // Ruta Inactiva
                g2.setColor(new Color(100, 150, 200, 90)); 
                g2.setStroke(new BasicStroke(2.0f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
            }
            g2.drawLine(a.nodoOrigen.getX(), a.nodoOrigen.getY(), 
                        a.nodoDestino.getX(), a.nodoDestino.getY());
        }

        Font fuenteNormal = new Font("Segoe UI", Font.BOLD, 11);
        Font fuenteCapital = new Font("Segoe UI", Font.BOLD, 14);

        // --- Nodos ---
        for (Nodo n : grafo.getVertices()) {
            int x = n.getX();
            int y = n.getY();
            String nombre = n.getMunicipio();

            g2.setColor(new Color(0, 0, 0, 70));
            g2.fillOval(x - 6, y - 6, 20, 20);

            g2.setColor(n.getColor());
            g2.fillOval(x - 9, y - 9, 18, 18);
            
            g2.setColor(Color.WHITE);
            g2.setStroke(new BasicStroke(2.5f));
            g2.drawOval(x - 9, y - 9, 18, 18);

            g2.setFont(nombre.equals("Oaxaca") ? fuenteCapital : fuenteNormal);
            int anchoTexto = g2.getFontMetrics().stringWidth(nombre);
            
            int textoX = x + 14;
            int textoY = y + 4;
            
            if (nombre.equals("Oaxaca")) {
                textoX = x - (anchoTexto / 2); textoY = y - 18;
            } else if (nombre.equals("Atzompa") || nombre.equals("J. Amilpas") || 
                       nombre.equals("Xoxocotlán") || nombre.equals("Zaachila")) {
                textoX = x - anchoTexto - 14;
            } else if (nombre.equals("Nochixtlán") || nombre.equals("Tuxtepec") || nombre.equals("Loma Bonita")) {
                textoX = x - (anchoTexto / 2); textoY = y - 14;
            }

            g2.setColor(new Color(255, 255, 255, 200));
            g2.drawString(nombre, textoX - 1, textoY - 1);
            g2.drawString(nombre, textoX + 1, textoY - 1);
            g2.drawString(nombre, textoX - 1, textoY + 1);
            g2.drawString(nombre, textoX + 1, textoY + 1);
            
            g2.setColor(nombre.equals("Oaxaca") ? new Color(180, 0, 0) : new Color(30, 40, 50));
            g2.drawString(nombre, textoX, textoY);
        }
    }
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

